export type NodeKind = 'claim' | 'frame' | 'metaphor';
export type NodeStance = 'reframe' | 'dominant' | 'catalytic';
export type AttachmentRole =
  | 'advances-reframe'
  | 'describes-dominant'
  | 'aims-catalytic';

export const NODE_KINDS: NodeKind[] = ['claim', 'frame', 'metaphor'];
export const NODE_STANCES: NodeStance[] = ['reframe', 'dominant', 'catalytic'];
export const ATTACHMENT_ROLES: { id: AttachmentRole; label: string }[] = [
  { id: 'advances-reframe', label: 'Advances the reframe' },
  { id: 'describes-dominant', label: 'Describes the dominant account' },
  { id: 'aims-catalytic', label: 'Aims at a catalytic community' },
];

export interface ClaimArgument {
  grounds?: string[];
  /** Source ids backing each ground, index-aligned with `grounds` */
  groundSources?: string[][];
  warrant?: string;
  qualifier?: string;
  rebuttal?: string;
  answer?: string;
}

export type SourceType = 'primary' | 'scholarship' | 'journalism' | 'reference';

export const SOURCE_TYPES: SourceType[] = [
  'primary',
  'scholarship',
  'journalism',
  'reference',
];

export interface SourceRecord {
  id: string;
  /** Full citation line (markdown-ish: *italics*, may end with a URL) */
  citation: string;
  url?: string;
  type?: SourceType;
  /** Where it is cited (regenerated by the sources build script) */
  citedBy?: { slug: string; footnoteId: string }[];
}

/** Stable id from a citation line: first author/institution + year-ish stem. */
export function slugifySourceId(citation: string): string {
  const stem = citation
    .replace(/https?:\/\/\S+/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .split('-')
    .slice(0, 6)
    .join('-');
  return `src-${stem || 'untitled'}`;
}

export function searchSources(sources: SourceRecord[], query: string): SourceRecord[] {
  const q = query.trim().toLowerCase();
  if (!q) return sources;
  return sources.filter(
    (s) =>
      s.id.toLowerCase().includes(q) ||
      s.citation.toLowerCase().includes(q) ||
      (s.type ?? '').includes(q),
  );
}

export type NodeOrigin = 'canonical' | 'adapted' | 'novel';

export const NODE_ORIGINS: { id: NodeOrigin; label: string }[] = [
  { id: 'canonical', label: 'Canonical — from the literature (CMT / FrameNet)' },
  { id: 'adapted', label: 'Adapted — canonical idea, project-specific form' },
  { id: 'novel', label: 'Novel — coined by this project' },
];

export interface TaxonomyNode {
  id: string;
  kind: NodeKind;
  label: string;
  stance: NodeStance;
  definition: string;
  /** Toulmin fields — used on claim nodes for the x-ray Argument tab */
  argument?: ClaimArgument;
  libraryRef?: string;
  /** Canonical (literature), adapted, or novel (project-coined) */
  origin?: NodeOrigin;
  /** Citation for the canonical/adapted source, e.g. "Lakoff & Johnson 1980" */
  source?: string;
  /** Claims form a tree: this claim supports its parent claim */
  parentId?: string;
  /** Frames/metaphors form rival systems: ids of the nodes this one counters */
  counters?: string[];
}

export interface Attachment {
  slug: string;
  /** `page` = page-level. Otherwise a block id like `block-3`. */
  blockId: string;
  /** First characters of the block at attach time, for recovery after reorder */
  excerpt: string;
  nodeId: string;
  role: AttachmentRole;
}

export interface TaxonomyMap {
  nodes: TaxonomyNode[];
}

export function slugifyNodeId(kind: NodeKind, label: string): string {
  const stem = label
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 48);
  return `${kind}-${stem || 'untitled'}`;
}

export function excerptOf(raw: string): string {
  return raw.replace(/\s+/g, ' ').trim().slice(0, 80);
}

export function searchNodes(nodes: TaxonomyNode[], query: string): TaxonomyNode[] {
  const q = query.trim().toLowerCase();
  if (!q) return nodes;
  return nodes.filter(
    (n) =>
      n.id.toLowerCase().includes(q) ||
      n.label.toLowerCase().includes(q) ||
      n.definition.toLowerCase().includes(q) ||
      n.kind.includes(q) ||
      n.stance.includes(q),
  );
}

export function formatMapIndex(nodes: TaxonomyNode[]): string {
  return nodes
    .map((n) => `- ${n.id} [${n.kind}/${n.stance}] ${n.label}`)
    .join('\n');
}

/** Children of a claim in the argument tree. */
export function childrenOf(nodes: TaxonomyNode[], id: string): TaxonomyNode[] {
  return nodes.filter((n) => n.parentId === id);
}

/** Nodes that this node counters, plus nodes that counter it (both directions). */
export function counterLinks(
  nodes: TaxonomyNode[],
  id: string,
): { counters: TaxonomyNode[]; counteredBy: TaxonomyNode[] } {
  const self = nodes.find((n) => n.id === id);
  const counters = (self?.counters ?? [])
    .map((cid) => nodes.find((n) => n.id === cid))
    .filter((n): n is TaxonomyNode => Boolean(n));
  const counteredBy = nodes.filter((n) => n.counters?.includes(id));
  return { counters, counteredBy };
}

/** Order claims as a tree (roots first, children indented via depth). */
export function claimTree(
  nodes: TaxonomyNode[],
): { node: TaxonomyNode; depth: number }[] {
  const claims = nodes.filter((n) => n.kind === 'claim');
  const ids = new Set(claims.map((n) => n.id));
  const roots = claims.filter((n) => !n.parentId || !ids.has(n.parentId));
  const out: { node: TaxonomyNode; depth: number }[] = [];
  const visit = (node: TaxonomyNode, depth: number, seen: Set<string>) => {
    if (seen.has(node.id)) return; // cycle guard
    seen.add(node.id);
    out.push({ node, depth });
    for (const child of claims.filter((c) => c.parentId === node.id)) {
      visit(child, depth + 1, seen);
    }
  };
  const seen = new Set<string>();
  for (const r of roots) visit(r, 0, seen);
  // Anything unreachable (shouldn't happen) still gets listed
  for (const c of claims) if (!seen.has(c.id)) out.push({ node: c, depth: 0 });
  return out;
}

/** "Crisis_response" and "crisis response" compare equal. */
function normalizeLabel(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}

/**
 * Pull one `### Heading` entry (heading + body, up to the next heading) out
 * of a reference library, matched against a map node's label.
 */
export function extractLibraryEntry(
  libraryText: string,
  label: string,
): string | null {
  if (!libraryText.trim()) return null;
  const target = normalizeLabel(label);
  const lines = libraryText.split('\n');
  for (let i = 0; i < lines.length; i++) {
    const m = lines[i].match(/^###\s+(.+)$/);
    if (!m || normalizeLabel(m[1]) !== target) continue;
    const body: string[] = [];
    for (let j = i + 1; j < lines.length; j++) {
      if (/^#{2,3}\s/.test(lines[j])) break;
      body.push(lines[j]);
    }
    return `${m[1].trim()}\n${body.join('\n').trim()}`.trim();
  }
  return null;
}
